name: 'dbt_packages_volio_group'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros", "dbt_packages/dbt_packages_volio_group/macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  
clean-targets:        
  - "target"
  - "dbt_packages"

tests:
  +severity: warn

vars:
  time_zone: "Asia/Ho_Chi_Minh"

  #device os system has 3 option: both_android_and_ios, android_only, ios_only. This var affect macro clean_firebase_device_os_version_data#
  device_os_system: 'both_android_and_ios'

  #number_day_backwards affect incremental model
  number_days_backwards: 7

  date_today: current_date('Asia/Ho_Chi_Minh')

  date_yesterday: date_sub(current_date('Asia/Ho_Chi_Minh'), interval 1 day)

  date_last_day_in_month: last_day(current_date('Asia/Ho_Chi_Minh'), month)

  date_last_2months: [
      date_trunc(date_sub(current_date('Asia/Ho_Chi_Minh'), interval 1 month), month),
      date_trunc(current_date('Asia/Ho_Chi_Minh'), month)
  ]